UploadBundle/Form/CropType.php
<?php

namespace Site\UploadBundle\Form;

use Symfony\Component\Validator\Constraints\Email;
use Symfony\Component\Validator\Constraints\Regex;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\Type;

class CropType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('w', 'number', array(
                'constraints'=>array(
                    new NotBlank(),
                    new Type(array('type'=>"numeric"))
                )
            ))
            ->add('h', 'number', array(
                'constraints'=>array(
                    new NotBlank(),
                    new Type(array('type'=>"numeric"))
                )
            ))
            ->add('x', 'number', array(
                'constraints'=>array(
                    new NotBlank(),
                    new Type(array('type'=>"numeric"))
                )
            ))
            ->add('y', 'number', array(
                'constraints'=>array(
                    new NotBlank(),
                    new Type(array('type'=>"numeric"))
                )
            ))
            ->add('x2', 'number', array(
                'constraints'=>array(
                    new NotBlank(),
                    new Type(array('type'=>"numeric"))
                )
            ))
            ->add('y2', 'number', array(
                'constraints'=>array(
                    new NotBlank(),
                    new Type(array('type'=>"numeric"))
                )
            ))
            ->add('path', 'text', array(
                'constraints'=>array(
                    new NotBlank(),
                    new Type(array('type'=>"string"))
                )
            ))
            ->add('field', 'text', array(
                'constraints'=>array(
                    new NotBlank(),
                    new Type(array('type'=>"string"))
                )
            ))
            ->add('type', 'text', array(
                'constraints'=>array(
                    new NotBlank(),
                    new Type(array('type'=>"string"))
                )
            ))
        ;
    }
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'csrf_protection' => false,
        ));
    }
//    public function setDefaultOptions(OptionsResolverInterface $resolver) {
//        /** @var OptionResolver $resolver */
//        $this->configureOptions($resolver);
//    }
    public function getName()
    {
        return 'site_uploadbundle_croptype';
    }
}

UploadBundle/Form/UpbeatUploadType.php
<?php

namespace Site\UploadBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;

class UpbeatUploadType extends AbstractType
{
    private $secureToken;
    public function __construct($csrfProvider, \Symfony\Component\HttpFoundation\Session\SessionInterface $session)
    {
        $this->secureToken = $csrfProvider->generateCsrfToken('');
        $session->set('secure_token', $this->secureToken);
    }


    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['file_type'] = $options['file_type'];
        $view->vars['template'] = $options['template'];
        $view->vars['extensions'] = $options['extensions'];
//        $view->vars['multi_selection'] = $options['multi_selection'];
        $view->vars['btn_name'] = $options['btn_name'];
        $view->vars['secure_token'] = $this->secureToken;
        $view->vars['use_plupload'] = $options['use_plupload'];
        $view->vars['crop'] = $options['crop'];
        $view->vars['crop_width'] = $options['crop_width'];
        $view->vars['crop_height'] = $options['crop_height'];
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'compound' => false,
            'multi_selection' => false,
            'class' => 'upload',
            'btn_name' => 'Upload',
            'file_type' => 'default',
            'template' => 'SiteUploadBundle:Upload:default.html.twig',
            'extensions' => '',
            'use_plupload' => true,
            'crop' => false,
            'crop_width'=>null,
            'crop_height'=>null
        ));
    }
//    public function setDefaultOptions(OptionsResolverInterface $resolver) {
//        /** @var OptionResolver $resolver */
//        $this->configureOptions($resolver);
//    }
    public function getParent()
    {
        return 'form';
    }

    public function getName()
    {
        return 'upbeat_upload_type';
    }
}

UploadBundle/Resources/views/SonataTheme/admin.theme.html.twig
{#
BLA-BLA-BlA
rewrite blocks for your own needs
#}

{% extends 'SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig' %}
{% block sonata_admin_orm_one_to_many_widget %}
    {% if sonata_admin.name == "files"  %}
        {% include 'SiteUploadBundle:SonataTheme:files_one_to_many.html.twig' %}
    {% else %}
        {% include 'SonataDoctrineORMAdminBundle:CRUD:edit_orm_one_to_many.html.twig' %}
    {% endif %}
{% endblock %}

UploadBundle/Resources/views/SonataTheme/edit_orm_one_association_script.html.twig
{#

This file is part of the Sonata package.

(c) Thomas Rabaix <thomas.rabaix@sonata-project.org>

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.

#}


{#

This code manage the one-to-many association field popup

#}

{% autoescape false %}

<!-- edit one association -->

<script type="text/javascript">

    // handle the add link
    var field_add_{{ id }} = function(event) {

        event.preventDefault();
        event.stopPropagation();

        var form = $(this).closest('form');

        // the ajax post
        $(form).ajaxSubmit({
            url: '{{ url('sonata_admin_append_form_element', {
                'code':      sonata_admin.admin.root.code,
                'elementId': id,
                'objectId':  sonata_admin.admin.root.id(sonata_admin.admin.root.subject),
                'uniqid':    sonata_admin.admin.root.uniqid
            } + sonata_admin.field_description.getOption('link_parameters', {})) }}',
            type: "POST",
            dataType: 'html',
            data: { _xml_http_request: true },
            success: function(html) {
                if (!html.length) {
                    return;
                }
                $('#field_container_{{ id }}').replaceWith(html); // replace the html
                Admin.shared_setup($('#field_container_{{ id }}'));

                if($('input[type="file"]', form).length > 0) {
                    $(form).attr('enctype', 'multipart/form-data');
                    $(form).attr('encoding', 'multipart/form-data');
                }
                $('#sonata-ba-field-container-{{ id }}').trigger('sonata.add_element');
                $('#field_container_{{ id }}').trigger('sonata.add_element');
            }
        });

        return false;
    };

    var field_widget_{{ id }} = false;

    // this function initialize the popup
    // this can be only done this way has popup can be cascaded
    function start_field_retrieve_{{ id }}(link) {

        link.onclick = null;

        // initialize component
        field_widget_{{ id }} = $("#field_widget_{{ id }}");

        // add the $ event to the a element
        $(link)
            .click(field_add_{{ id }})
            .trigger('click')
        ;

        return false;
    }
</script>

<!-- / edit one association -->

{% endautoescape %}

UploadBundle/Resources/views/SonataTheme/files_one_to_many.html.twig
{#

This file is part of the Sonata package.

(c) Thomas Rabaix <thomas.rabaix@sonata-project.org>

For the full copyright and license information, please view the LICENSE
file that was distributed with this source code.

#}
{% if not sonata_admin.field_description.hasassociationadmin %}
    {% for element in value %}
        {{ element|render_relation_element(sonata_admin.field_description) }}
    {% endfor %}
{% else %}
    <div id="field_container_{{ id }}" class="field-container">
        <span id="field_widget_{{ id }}" >
            {% if sonata_admin.edit == 'inline' %}
                {% if sonata_admin.inline == 'table' %}
                    {% if form.children|length > 0 %}
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                {% for field_name, nested_field in form.children|first.children %}
                                    {% if field_name == '_delete' %}
                                        <th>{{ 'action_delete'|trans({}, 'SonataAdminBundle') }}</th>
                                    {% else %}
                                        <th {{ nested_field.vars['required']  ? 'class="required"' : '' }}{% if (nested_field.vars['attr']['hidden'] is defined) and (nested_field.vars['attr']['hidden']) %} style="display:none;"{% endif %}>
                                            {{ nested_field.vars['sonata_admin'].admin.trans(nested_field.vars.label) }}
                                        </th>
                                    {% endif %}
                                {% endfor %}
                            </tr>
                            </thead>
                            <tbody class="sonata-ba-tbody">
                            {% for nested_group_field_name, nested_group_field in form.children %}
                                <tr>
                                    {% for field_name, nested_field in nested_group_field.children %}
                                        <td class="sonata-ba-td-{{ id }}-{{ field_name  }} control-group{% if nested_field.vars.errors|length > 0 %} error{% endif %}"{% if (nested_field.vars['attr']['hidden'] is defined) and (nested_field.vars['attr']['hidden']) %} style="display:none;"{% endif %}>
                                            {% if sonata_admin.field_description.associationadmin.formfielddescriptions[field_name] is defined %}
                                                {{ form_widget(nested_field) }}
                                                {% set dummy = nested_group_field.setrendered %}
                                            {% else %}
                                                {% if field_name == '_delete' %}
                                                    {{ form_widget(nested_field, {'label_render': false}) }}
                                                {% else %}
                                                    {{ form_widget(nested_field) }}
                                                {% endif %}
                                            {% endif %}
                                            {% if nested_field.vars.errors|length > 0 %}
                                                <div class="help-inline sonata-ba-field-error-messages">
                                                    {{ form_errors(nested_field) }}
                                                </div>
                                            {% endif %}
                                        </td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    {% endif %}
                    {#end inline table#}
                {% elseif form.children|length > 0 %}
                    {% set associationAdmin = sonata_admin.field_description.associationadmin %}

                    <div>
                        {% for nested_group_field in form.children %}
                            <ul class="nav nav-tabs">
                                {% for name, form_group in associationAdmin.formgroups %}
                                    <li class="{% if loop.first %}active{% endif %}">
                                        <a href="#{{ associationAdmin.uniqid }}_{{ loop.parent.loop.index }}_{{ loop.index }}" data-toggle="tab">
                                            <i class="icon-exclamation-sign has-errors hide"></i>
                                            {{ associationAdmin.trans(name, {}, form_group.translation_domain) }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>

                            <div class="tab-content">
                                {% for name, form_group in associationAdmin.formgroups %}
                                    <div class="tab-pane {% if loop.first %}active{% endif %}" id="{{ associationAdmin.uniqid }}_{{ loop.parent.loop.index }}_{{ loop.index }}">
                                        <fieldset>
                                            <div class="sonata-ba-collapsed-fields">
                                                {% for field_name in form_group.fields %}
                                                    {% set nested_field = nested_group_field.children[field_name] %}
                                                    {% if associationAdmin.formfielddescriptions[field_name] is defined %}
                                                        {{ form_row(nested_field, {
                                                            'inline': 'natural',
                                                            'edit'  : 'inline'
                                                        }) }}
                                                        {% set dummy = nested_group_field.setrendered %}
                                                    {% else %}
                                                        {{ form_row(nested_field) }}
                                                    {% endif %}
                                                {% endfor %}
                                            </div>
                                        </fieldset>
                                    </div>
                                {% endfor %}
                            </div>

                            {% if nested_group_field['_delete'] is defined %}
                                {{ form_row(nested_group_field['_delete']) }}
                            {% endif %}
                        {% endfor %}
                    </div>
                {% endif %}
            {% else %}
                {{ form_widget(form) }}
            {% endif %}

        </span>

        {% if sonata_admin.edit == 'inline' %}
            {% if sonata_admin.field_description.associationadmin.hasroute('create') and sonata_admin.field_description.associationadmin.isGranted('CREATE') and btn_add %}
                <span id="field_actions_{{ id }}" >
                    <a
                            href="{{ sonata_admin.field_description.associationadmin.generateUrl('create', sonata_admin.field_description.getOption('link_parameters', {})) }}"
                            onclick="return start_field_retrieve_{{ id }}(this);"
                            class="btn btn-success btn-sm btn-outline sonata-ba-action"
                            title="{{ btn_add|trans({}, btn_catalogue) }}"
                            >
                        <i class="fa fa-plus-circle"></i>
                        {{ btn_add|trans({}, btn_catalogue) }}
                    </a>
                </span>
            {% endif %}

            {# add code for the sortable options #}
            {% if sonata_admin.field_description.options.sortable is defined %}
                <script type="text/javascript">
                    jQuery('div#field_container_{{ id }} tbody.sonata-ba-tbody').sortable({
                        axis: 'y',
                        opacity: 0.6,
                        items: '> tr',
                        stop: apply_position_value_{{ id }}
                    });

                    function apply_position_value_{{ id }}() {
                        // update the input value position
                        jQuery('div#field_container_{{ id }} tbody.sonata-ba-tbody td.sonata-ba-td-{{ id }}-{{ sonata_admin.field_description.options.sortable }}').each(function(index, element) {
                            // remove the sortable handler and put it back
                            jQuery('span.sonata-ba-sortable-handler', element).remove();
                            jQuery(element).append('<span class="sonata-ba-sortable-handler ui-icon ui-icon-grip-solid-horizontal"></span>');
                            jQuery('input', element).hide();
                        });

                        jQuery('div#field_container_{{ id }} tbody.sonata-ba-tbody td.sonata-ba-td-{{ id }}-{{ sonata_admin.field_description.options.sortable }} input').each(function(index, value) {
                            jQuery(value).val(index + 1);
                        });
                    }

                    // refresh the sortable option when a new element is added
                    jQuery('#sonata-ba-field-container-{{ id }}').bind('sonata.add_element', function() {
                        apply_position_value_{{ id }}();
                        jQuery('div#field_container_{{ id }} tbody.sonata-ba-tbody').sortable('refresh');
                    });

                    apply_position_value_{{ id }}();

                </script>
            {% endif %}

            {# include association code #}
            {% include 'SiteUploadBundle:SonataTheme:edit_orm_one_association_script.html.twig' %}

        {% else %}
            <span id="field_actions_{{ id }}" >
                {% if sonata_admin.field_description.associationadmin.hasroute('create') and sonata_admin.field_description.associationadmin.isGranted('CREATE') and btn_add %}
                    <a
                            href="{{ sonata_admin.field_description.associationadmin.generateUrl('create', sonata_admin.field_description.getOption('link_parameters', {})) }}"
                            onclick="return start_field_dialog_form_add_{{ id }}(this);"
                            class="btn btn-success btn-sm btn-outline sonata-ba-action"
                            title="{{ btn_add|trans({}, btn_catalogue) }}"
                            >
                        <i class="fa fa-plus-circle"></i>
                        {{ btn_add|trans({}, btn_catalogue) }}
                    </a>
                {% endif %}
            </span>

            {% include 'SonataDoctrineORMAdminBundle:CRUD:edit_modal.html.twig' %}
            {% include 'SonataDoctrineORMAdminBundle:CRUD:edit_orm_many_association_script.html.twig' %}
        {% endif %}
    </div>
{% endif %}